services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=ifeanyidike
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_SOURCE=postgresql://ifeanyidike:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    # entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    # command: ["/app/main"]
