services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
      - POSTGRES_HOST=postgres
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    # command: ["./start.sh"]
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
